// constants/theme.ts
export const Colors = {
  light: {
    background: '#FAFAFA',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    primary: '#E64A19',       // Vibrant Orange
    primaryForeground: '#FFFFFF',
    secondary: '#F5F5F5',
    secondaryForeground: '#333333',
    muted: '#F0F0F0',
    mutedForeground: '#737373',
    accent: '#F5F5F5',
    accentForeground: '#222222',
    destructive: '#D32F2F',
    destructiveForeground: '#FFFFFF',
    success: '#388E3C',
    successForeground: '#FFFFFF',
    successLight: '#E8F5E9',
    warning: '#F57C00',
    warningForeground: '#1A1A1A',
    warningLight: '#FFF3E0',
    dangerLight: '#FFEBEE',
    border: '#E8E8E8',
    input: '#E8E8E8',
    ring: '#E64A19',
  },
  dark: {
    background: '#121212',
    foreground: '#F0F0F0',
    card: '#1E1E1E',
    cardForeground: '#F0F0F0',
    primary: '#FF7043',
    primaryForeground: '#1A1A1A',
    secondary: '#2A2A2A',
    secondaryForeground: '#F0F0F0',
    muted: '#2A2A2A',
    mutedForeground: '#A0A0A0',
    accent: '#2A2A2A',
    accentForeground: '#F0F0F0',
    destructive: '#EF5350',
    destructiveForeground: '#F0F0F0',
    success: '#66BB6A',
    successForeground: '#1A1A1A',
    successLight: '#1B3A1D',
    warning: '#FFA726',
    warningForeground: '#1A1A1A',
    warningLight: '#3D2800',
    dangerLight: '#3D1A1A',
    border: '#2E2E2E',
    input: '#2E2E2E',
    ring: '#FF7043',
  },
}

export type ColorScheme = 'light' | 'dark'
export type ThemeColors = typeof Colors.light
